local wezterm = require 'wezterm'

return {
  adjust_window_size_when_changing_font_size = false,
  allow_square_glyphs_to_overflow_width = "WhenFollowedBySpace",
  allow_win32_input_mode = false,
  alternate_buffer_wheel_scroll_speed = 3,
  animation_fps = 1,
  anti_alias_custom_block_glyphs = true,
  automatically_reload_config = true,
  audible_bell = "Disabled",
  bold_brightens_ansi_colors = "BrightAndBold",
  bypass_mouse_reporting_modifiers = "SHIFT",
  canonicalize_pasted_newlines = "LineFeed",
  cell_width = 1.0,
  char_select_bg_color = "#333333",
  char_select_fg_color = 'rgba(0.75, 0.75, 0.75, 1.0)',
  char_select_font_size = 14.0,
  check_for_updates = false,
  check_for_updates_interval_seconds = 86400,
  clean_exit_codes = { 130 },
  colors = {
    foreground = "#fbf1c7",
    background = "#282828",
    ansi = {
      "#282828",
      "#cc241d",
      "#98971a",
      "#d79921",
      "#458588",
      "#b16286",
      "#689d6a",
      "#a89984",
    },
    brights = {
      "#928374",
      "#fb4934",
      "#b8bb26",
      "#fabd2f",
      "#83a598",
      "#d3869b",
      "#8ec07c",
      "#ebdbb2",
    },
    selection_fg = '#282828',
    selection_bg = '#fbf1c7',
  },
  command_palette_bg_color = "#333333",
  command_palette_fg_color = "rgba(0.75, 0.75, 0.75, 1.0)",
  command_palette_font_size = 14.0,
  command_palette_rows = 14,
  cursor_blink_ease_in = "Linear",
  cursor_blink_ease_out = "Linear",
  cursor_blink_rate = 0,
  cursor_thickness = 1,
  custom_block_glyphs = true,
  debug_key_events = false,
  default_cursor_style = "SteadyBlock",
  default_cwd = wezterm.home_dir,
  default_domain = "local",
  default_gui_startup_args = { "start" },
  default_mux_server_domain = "local",
  default_prog = { "/usr/bin/bash" },
  default_workspace = "default",
  detect_password_input = true,
  disable_default_mouse_bindings = false,
  disable_default_quick_select_patterns = false,
  display_pixel_geometry = "RGB",
  dpi = 96,
  enable_csi_u_key_encoding = false,
  enable_scroll_bar = false,
  enable_tab_bar = true,
  enable_wayland = true,
  exit_behavior = "CloseOnCleanExit",
  exit_behavior_messaging = "Verbose",
  font = wezterm.font 'JetBrainsMono NF',
  font_rasterizer = "FreeType",
  font_shaper = "Harfbuzz",
  font_size = 11.0,
  force_reverse_video_cursor = true,
  freetype_interpreter_version = 40,
  freetype_load_target = "Normal",
  hide_mouse_cursor_when_typing = true,
  hide_tab_bar_if_only_one_tab = true,
  integrated_title_button_color = "blue",
  integrated_title_button_style = "Gnome",
  integrated_title_buttons = { "Close" },
  integrated_title_button_alignment = "Left",
  line_height = 1.0,
  -- show_close_tab_button_in_tabs = false,
  show_new_tab_button_in_tab_bar = true,
  show_update_window = false,
  strikethrough_position = "0.5cell",
  tab_bar_at_bottom = false,
  ui_key_cap_rendering = "UnixLong",
  unicode_version = 14,
  use_fancy_tab_bar = true,
  use_ime = false,
  use_resize_increments = false,
  window_decorations = "TITLE | RESIZE",
  window_frame = {
    font = wezterm.font 'Inter',
  },
  window_padding = {
    left = 5,
    right = 5,
    top = 5,
    bottom = 5,
  },
}
