[theme]
# dark = "gruvbox_dark_hard"
# light = "gruvbox_light_hard"
dark = "jellybeans"
light = "adwaita-light"

[editor.cursor-shape]
insert = "bar"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 400
