# This file will be merged with this: https://github.com/helix-editor/helix/blob/master/languages.toml
# but inline tables and arrays are not merged.

[language-server]
harper = { command = "harper-ls", args = ["--stdio"] }
rumdl = { command = "rumdl", args = ["server"] }
scls = { command = "simple-completion-language-server" }
codebook = { command="codebook-lsp", args = ["serve"] }
eslint = { command = "eslint-language-server", args = ["--stdio"] }

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "scls", "codebook"]

[[language]]
name = "git-commit"
language-servers = ["harper", "codebook"]

[[language]]
name = "markdown"
soft-wrap = { enable = true, wrap-at-text-width = false }
language-servers = ["marksman", "rumdl", "harper", "codebook"]

[[language]]
name = "typst"
soft-wrap = { enable = true, wrap-at-text-width = true }
language-servers = ["tinymist", "harper", "codebook"]

[[language]]
name = "xml"
file-types = ["xml", "svg", "rss", "atom", "ui", "doap", { glob = "fontconfig/fonts.conf" }]
language-servers = ["harper", "codebook"]

[[language]]
name = "toml"
formatter = { command = "tombi", args = ["format"] }

[[language]]
name = "svelte"
language-servers = ["svelteserver", "eslint", "codebook"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "svelte"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint", "codebook"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "ts"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint", "codebook"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "js"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml", "harper", "codebook"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "codebook"]
auto-format = true
