include=/home/mario/.config/foot/theme-dark.ini

[main]
font=JetBrainsMono Nerd Font:size=10
font-size-adjustment=10%
line-height=18px
underline-offset=50
#underline-thickness=5px
pad=5x5

[cursor]
#color=665c54 bdae93
beam-thickness=1

[csd]
preferred=none
