#!/bin/bash

# Find the default input source
# Since getting the source evry second is useless and resource intensive
# $source is set one time in a sessione by ~/.config/zsh/environment, like so

source=$WP_SOURCE_ID

status=$(wpctl status | rg "Analog:capture_FR" | cut -d "[" -f 2 | cut -d "]" -f 1)
isMuted=$(wpctl get-volume $source | rg MUTED)

if [[ $status == "active" ]]; then
  class="recording"
  text=""
else
  class="inactive"
  text=""
fi

if [[ $isMuted ]]; then
  if [[ $class == recording ]]; then
    class="recording-muted"
  else
    class="muted"
  fi

  text=""
fi

tooltip="Status: $class, $(wpctl get-volume $source)"

echo -e "$text\n$tooltip\n$class"
